name: Deploy to Minikube

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted  # Your Minikube-connected runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set image tag
        run: |
          sed -i 's|image: .*|image: praveengangala/my-app:latest|' k8s/deployment.yaml

      - name: Apply to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f ingress.yaml
          kubectl rollout status deployment/my-app
