name: Build & Deploy to Minikube

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./my-app
        file: ./my-app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Minikube
      uses: medyagh/setup-minikube@v2

    - name: Enable Ingress and Traefik
      run: |
        minikube addons enable ingress
        minikube addons enable traefik

    - name: Replace image in deployment.yaml
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_IMAGE }}:latest|" k8s/deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml

    - name: Wait for app to become available
      run: |
        sleep 20
        kubectl get all
