name: CI-CD
on:
  push:
    branches:
      - main
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build & push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USER }}/real-webapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
    - uses: actions/checkout@v3
    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
